services:
  checker:
    build:
      target: development
    restart: unless-stopped
    volumes:
      - "./src:/usr/src/app/src"
      - "./tsconfig.json:/usr/src/app/tsconfig.json"
    environment:
      INTERVAL_MINUTES: ${INTERVAL_MINUTES}
      NOTIFICATION_TIMEOUT_MINUTES: ${NOTIFICATION_TIMEOUT_MINUTES}
      USERNAMES: ${USERNAMES}
      DISCORD_USER_IDS: ${DISCORD_USER_IDS}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
